/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import com.jtattoo.plaf.mint.MintLookAndFeel;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.LookAndFeel;
import javax.swing.UIManager;
import com.jtattoo.plaf.mint.MintLookAndFeel;
import control.koneksi;
import control.laporan;
import control.utama;

import java.awt.Dialog;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UnsupportedLookAndFeelException;
import keeptoo.Drag;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.data.category.DefaultCategoryDataset;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author handa
 */
public class FormUtama extends javax.swing.JFrame {
 
Color DefaultColor,ClickedColor; 
    

    /**
     * Creates new form FormUtama
     */
    Connection conn;
    public FormUtama() {
        initComponents();
        DefaultColor=new Color(102,0,0);
        ClickedColor= new Color(255,153,0);
        
        Menu1.setBackground(DefaultColor);
        Menu2.setBackground(DefaultColor);
        Menu3.setBackground(DefaultColor);
        Menu4.setBackground(DefaultColor);
        Menu5.setBackground(DefaultColor);
        Menu6.setBackground(DefaultColor);
        
        koneksi kon = new koneksi();
        kon.setKoneksi();
        conn = kon.getKoneksi();
        totalTrx2.setText(String.valueOf(getTotalPenjualan()));
        totalBrg.setText(String.valueOf(getTotalBarang()));
        totalPlg.setText(String.valueOf(getTotalPelanggan()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MainPanel = new custom.RoundedDesktopPane();
        kGradientPanel6 = new keeptoo.KGradientPanel();
        TotalTransaksi2 = new javax.swing.JLabel();
        totalTrx2 = new javax.swing.JLabel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        totalBrg = new javax.swing.JLabel();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        totalPlg = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        Menu6 = new javax.swing.JPanel();
        txRiwayat = new javax.swing.JLabel();
        Menu5 = new javax.swing.JPanel();
        txPelanggan = new javax.swing.JLabel();
        Menu4 = new javax.swing.JPanel();
        txTransaksi = new javax.swing.JLabel();
        Menu3 = new javax.swing.JPanel();
        txBarang = new javax.swing.JLabel();
        Menu2 = new javax.swing.JPanel();
        txUser = new javax.swing.JLabel();
        Menu1 = new javax.swing.JPanel();
        txUser1 = new javax.swing.JLabel();
        pengguna = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel6.setkEndColor(new java.awt.Color(255, 153, 51));
        kGradientPanel6.setkStartColor(new java.awt.Color(255, 153, 51));

        TotalTransaksi2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TotalTransaksi2.setForeground(new java.awt.Color(255, 255, 255));
        TotalTransaksi2.setText("Total Transaksi");

        totalTrx2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totalTrx2.setForeground(new java.awt.Color(255, 255, 255));
        totalTrx2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totalTrx2.setText("0");

        javax.swing.GroupLayout kGradientPanel6Layout = new javax.swing.GroupLayout(kGradientPanel6);
        kGradientPanel6.setLayout(kGradientPanel6Layout);
        kGradientPanel6Layout.setHorizontalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel6Layout.createSequentialGroup()
                        .addComponent(TotalTransaksi2)
                        .addGap(0, 108, Short.MAX_VALUE))
                    .addComponent(totalTrx2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        kGradientPanel6Layout.setVerticalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TotalTransaksi2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(totalTrx2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MainPanel.add(kGradientPanel6);
        kGradientPanel6.setBounds(10, 20, 240, 110);

        kGradientPanel4.setkEndColor(new java.awt.Color(255, 153, 51));
        kGradientPanel4.setkGradientFocus(400);
        kGradientPanel4.setkStartColor(new java.awt.Color(255, 153, 51));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jumlah Barang");

        totalBrg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totalBrg.setForeground(new java.awt.Color(255, 255, 255));
        totalBrg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totalBrg.setText("0");

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 142, Short.MAX_VALUE))
                    .addComponent(totalBrg, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                .addContainerGap())
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(totalBrg)
                .addContainerGap())
        );

        MainPanel.add(kGradientPanel4);
        kGradientPanel4.setBounds(270, 20, 260, 110);

        kGradientPanel5.setkEndColor(new java.awt.Color(255, 153, 51));
        kGradientPanel5.setkStartColor(new java.awt.Color(255, 153, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jumlah Pelanggan");

        totalPlg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totalPlg.setForeground(new java.awt.Color(255, 255, 255));
        totalPlg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totalPlg.setText("0");

        javax.swing.GroupLayout kGradientPanel5Layout = new javax.swing.GroupLayout(kGradientPanel5);
        kGradientPanel5.setLayout(kGradientPanel5Layout);
        kGradientPanel5Layout.setHorizontalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 141, Short.MAX_VALUE))
                    .addComponent(totalPlg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        kGradientPanel5Layout.setVerticalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(totalPlg)
                .addContainerGap())
        );

        MainPanel.add(kGradientPanel5);
        kGradientPanel5.setBounds(560, 20, 280, 110);

        jPanel1.add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 880, 490));

        logout.setFont(new java.awt.Font("Modern No. 20", 1, 17)); // NOI18N
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, 60, 20));

        Menu6.setBackground(new java.awt.Color(102, 0, 0));
        Menu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu6MousePressed(evt);
            }
        });

        txRiwayat.setFont(new java.awt.Font("Modern No. 20", 1, 16)); // NOI18N
        txRiwayat.setForeground(new java.awt.Color(255, 255, 255));
        txRiwayat.setText("Riwayat");
        txRiwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txRiwayatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Menu6Layout = new javax.swing.GroupLayout(Menu6);
        Menu6.setLayout(Menu6Layout);
        Menu6Layout.setHorizontalGroup(
            Menu6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu6Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(txRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        Menu6Layout.setVerticalGroup(
            Menu6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txRiwayat, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(Menu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 180, 60));

        Menu5.setBackground(new java.awt.Color(102, 0, 0));
        Menu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu5MousePressed(evt);
            }
        });

        txPelanggan.setFont(new java.awt.Font("Modern No. 20", 1, 16)); // NOI18N
        txPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        txPelanggan.setText("Pelanggan");
        txPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txPelangganMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Menu5Layout = new javax.swing.GroupLayout(Menu5);
        Menu5.setLayout(Menu5Layout);
        Menu5Layout.setHorizontalGroup(
            Menu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu5Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(txPelanggan)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        Menu5Layout.setVerticalGroup(
            Menu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(Menu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 180, 60));

        Menu4.setBackground(new java.awt.Color(102, 0, 0));
        Menu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu4MousePressed(evt);
            }
        });

        txTransaksi.setFont(new java.awt.Font("Modern No. 20", 1, 16)); // NOI18N
        txTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        txTransaksi.setText("Transaksi");
        txTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txTransaksiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Menu4Layout = new javax.swing.GroupLayout(Menu4);
        Menu4.setLayout(Menu4Layout);
        Menu4Layout.setHorizontalGroup(
            Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu4Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(txTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        Menu4Layout.setVerticalGroup(
            Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(Menu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 180, 60));

        Menu3.setBackground(new java.awt.Color(102, 0, 0));
        Menu3.setMaximumSize(new java.awt.Dimension(32765, 32765));
        Menu3.setPreferredSize(new java.awt.Dimension(180, 45));
        Menu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu3MousePressed(evt);
            }
        });

        txBarang.setFont(new java.awt.Font("Modern No. 20", 1, 15)); // NOI18N
        txBarang.setForeground(new java.awt.Color(255, 255, 255));
        txBarang.setText("Barang");
        txBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txBarangMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Menu3Layout = new javax.swing.GroupLayout(Menu3);
        Menu3.setLayout(Menu3Layout);
        Menu3Layout.setHorizontalGroup(
            Menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu3Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(txBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        Menu3Layout.setVerticalGroup(
            Menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(Menu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 180, 50));

        Menu2.setBackground(new java.awt.Color(102, 0, 0));
        Menu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu2MousePressed(evt);
            }
        });

        txUser.setFont(new java.awt.Font("Modern No. 20", 1, 16)); // NOI18N
        txUser.setForeground(new java.awt.Color(255, 255, 255));
        txUser.setText("User");
        txUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txUserMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Menu2Layout = new javax.swing.GroupLayout(Menu2);
        Menu2.setLayout(Menu2Layout);
        Menu2Layout.setHorizontalGroup(
            Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu2Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(txUser)
                .addGap(78, 78, 78))
        );
        Menu2Layout.setVerticalGroup(
            Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txUser, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(Menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 180, 50));

        Menu1.setBackground(new java.awt.Color(102, 0, 0));
        Menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu1MousePressed(evt);
            }
        });

        txUser1.setFont(new java.awt.Font("Modern No. 20", 1, 16)); // NOI18N
        txUser1.setForeground(new java.awt.Color(255, 255, 255));
        txUser1.setText("Home");
        txUser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txUser1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Menu1Layout = new javax.swing.GroupLayout(Menu1);
        Menu1.setLayout(Menu1Layout);
        Menu1Layout.setHorizontalGroup(
            Menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(txUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        Menu1Layout.setVerticalGroup(
            Menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txUser1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(Menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 180, 50));

        pengguna.setFont(new java.awt.Font("Modern No. 20", 1, 16)); // NOI18N
        pengguna.setText("User");
        pengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penggunaMouseClicked(evt);
            }
        });
        jPanel1.add(pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/DASHBOARD (2).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public int getTotalPenjualan() {
        int total = 0;
        String sql = "SELECT count(*) AS total_penjualan FROM penjualan";

        try {
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                total = rs.getInt("total_penjualan");
            }

            rs.close();
            stmt.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return total;
    }
    
    public int getTotalBarang() {
        int total = 0;
        String sql = "SELECT COUNT(*) AS total_barang FROM masterbarang";

        try {
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                total = rs.getInt("total_barang");
            }

            rs.close();
            stmt.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return total;
    }
    
    public int getTotalPelanggan() {
        int total = 0;
        String sql = "SELECT COUNT(*) AS total_pelanggan FROM pelanggan";

        try {
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                total = rs.getInt("total_pelanggan");
            }

            rs.close();
            stmt.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return total;
    }
    private void txUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txUserMouseClicked
        
    }//GEN-LAST:event_txUserMouseClicked

    private void txBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txBarangMouseClicked
       
    }//GEN-LAST:event_txBarangMouseClicked

    private void txTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txTransaksiMouseClicked
        
    }//GEN-LAST:event_txTransaksiMouseClicked

    private void txPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txPelangganMouseClicked
       
    }//GEN-LAST:event_txPelangganMouseClicked

    private void txRiwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txRiwayatMouseClicked
       
    }//GEN-LAST:event_txRiwayatMouseClicked

    private void penggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penggunaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_penggunaMouseClicked

    private void Menu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu1MousePressed
        Menu1.setBackground(ClickedColor);
        Menu2.setBackground(DefaultColor);
        Menu3.setBackground(DefaultColor);
        Menu4.setBackground(DefaultColor);
        Menu5.setBackground(DefaultColor);
        Menu6.setBackground(DefaultColor);
    }//GEN-LAST:event_Menu1MousePressed

    private void Menu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu2MousePressed
        Menu1.setBackground(DefaultColor);
        Menu2.setBackground(ClickedColor);
        Menu3.setBackground(DefaultColor);
        Menu4.setBackground(DefaultColor);
        Menu5.setBackground(DefaultColor);
        Menu6.setBackground(DefaultColor);
    }//GEN-LAST:event_Menu2MousePressed

    private void Menu3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu3MousePressed
        Menu1.setBackground(DefaultColor);
        Menu2.setBackground(DefaultColor);
        Menu3.setBackground(ClickedColor);
        Menu4.setBackground(DefaultColor);
        Menu5.setBackground(DefaultColor);
        Menu6.setBackground(DefaultColor);
    }//GEN-LAST:event_Menu3MousePressed

    private void Menu4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu4MousePressed
        Menu1.setBackground(DefaultColor);
        Menu2.setBackground(DefaultColor);
        Menu3.setBackground(DefaultColor);
        Menu4.setBackground(ClickedColor);
        Menu5.setBackground(DefaultColor);
        Menu6.setBackground(DefaultColor);
    }//GEN-LAST:event_Menu4MousePressed

    private void Menu5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu5MousePressed
        Menu1.setBackground(DefaultColor);
        Menu2.setBackground(DefaultColor);
        Menu3.setBackground(DefaultColor);
        Menu4.setBackground(DefaultColor);
        Menu5.setBackground(ClickedColor);
        Menu6.setBackground(DefaultColor);
    }//GEN-LAST:event_Menu5MousePressed

    private void Menu6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu6MousePressed
        Menu1.setBackground(DefaultColor);
        Menu2.setBackground(DefaultColor);
        Menu3.setBackground(DefaultColor);
        Menu4.setBackground(DefaultColor);
        Menu5.setBackground(DefaultColor);
        Menu6.setBackground(ClickedColor);
    }//GEN-LAST:event_Menu6MousePressed

    private void Menu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu2MouseClicked
        User user=new User();
        MainPanel.removeAll();
        MainPanel.add(user).setVisible(true);
    }//GEN-LAST:event_Menu2MouseClicked

    private void Menu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu3MouseClicked
        FormBarang frmBarang=new FormBarang();
        MainPanel.removeAll();
        MainPanel.add(frmBarang).setVisible(true);
    }//GEN-LAST:event_Menu3MouseClicked

    private void Menu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu4MouseClicked
        Transaksi transaksi=new Transaksi();
        MainPanel.removeAll();
        MainPanel.add(transaksi).setVisible(true);
    }//GEN-LAST:event_Menu4MouseClicked

    private void Menu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu1MouseClicked
        
        FormHome Home=new FormHome();
        MainPanel.removeAll();
        MainPanel.add(Home).setVisible(true);
       
    }//GEN-LAST:event_Menu1MouseClicked

    private void Menu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu5MouseClicked
        FormPelanggan pelanggan=new FormPelanggan();
        MainPanel.removeAll();
        MainPanel.add(pelanggan).setVisible(true);
    }//GEN-LAST:event_Menu5MouseClicked

    private void Menu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu6MouseClicked
        FormHistory histori=new FormHistory();
        MainPanel.removeAll();
        MainPanel.add(histori).setVisible(true);
    }//GEN-LAST:event_Menu6MouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
       int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin logout?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {

        this.dispose();

       
        new Login().setVisible(true);
    }
    }//GEN-LAST:event_logoutMouseClicked

    private void txUser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txUser1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txUser1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
             UIManager.setLookAndFeel(new FlatLightLaf());
             UIManager.put("defaultFont", new java.awt.Font("Poppins", java.awt.Font.PLAIN, 14));
        } catch (Exception e) {
            
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private custom.RoundedDesktopPane MainPanel;
    private javax.swing.JPanel Menu1;
    private javax.swing.JPanel Menu2;
    private javax.swing.JPanel Menu3;
    private javax.swing.JPanel Menu4;
    private javax.swing.JPanel Menu5;
    private javax.swing.JPanel Menu6;
    private javax.swing.JLabel TotalTransaksi2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    public keeptoo.KGradientPanel kGradientPanel6;
    public static javax.swing.JLabel logout;
    public static javax.swing.JLabel pengguna;
    public static javax.swing.JLabel totalBrg;
    public static javax.swing.JLabel totalPlg;
    public static javax.swing.JLabel totalTrx2;
    private javax.swing.JLabel txBarang;
    private javax.swing.JLabel txPelanggan;
    private javax.swing.JLabel txRiwayat;
    private javax.swing.JLabel txTransaksi;
    private javax.swing.JLabel txUser;
    private javax.swing.JLabel txUser1;
    // End of variables declaration//GEN-END:variables
}
