/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gui;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import control.koneksi;
import static gui.FormUtama.totalBrg;
import static gui.FormUtama.totalPlg;
import static gui.FormUtama.totalTrx;
import java.sql.Connection;
import javax.swing.JOptionPane;
/**
 *
 * @author handa
 */
public class FormHome extends javax.swing.JInternalFrame {

   Connection conn;

    /**
     * Creates new form FormHome
     */
    public FormHome() {
        initComponents();
           this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        koneksi kon = new koneksi();
        kon.setKoneksi();
        conn = kon.getKoneksi();
        FormUtama.totalTrx.setText(String.valueOf(getTotalPenjualan()));
        totalBrg.setText(String.valueOf(getTotalBarang()));
        totalPlg.setText(String.valueOf(getTotalPelanggan()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedDesktopPane1 = new custom.RoundedDesktopPane();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        totalBrg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        totalPlg = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kGradientPanel6 = new keeptoo.KGradientPanel();
        TotalTransaksi2 = new javax.swing.JLabel();
        totalTrx = new javax.swing.JLabel();

        kGradientPanel4.setkEndColor(new java.awt.Color(255, 153, 51));
        kGradientPanel4.setkGradientFocus(400);
        kGradientPanel4.setkStartColor(new java.awt.Color(255, 153, 51));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jumlah Barang");

        totalBrg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totalBrg.setForeground(new java.awt.Color(255, 255, 255));
        totalBrg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totalBrg.setText("0");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Rp.");

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(kGradientPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(totalBrg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalBrg)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        roundedDesktopPane1.add(kGradientPanel4);
        kGradientPanel4.setBounds(270, 20, 260, 110);

        kGradientPanel5.setkEndColor(new java.awt.Color(255, 153, 51));
        kGradientPanel5.setkStartColor(new java.awt.Color(255, 153, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jumlah Pelanggan");

        totalPlg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totalPlg.setForeground(new java.awt.Color(255, 255, 255));
        totalPlg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totalPlg.setText("0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Rp.");

        javax.swing.GroupLayout kGradientPanel5Layout = new javax.swing.GroupLayout(kGradientPanel5);
        kGradientPanel5.setLayout(kGradientPanel5Layout);
        kGradientPanel5Layout.setHorizontalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(kGradientPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalPlg, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 80, Short.MAX_VALUE))))
        );
        kGradientPanel5Layout.setVerticalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPlg)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        roundedDesktopPane1.add(kGradientPanel5);
        kGradientPanel5.setBounds(560, 20, 280, 110);

        kGradientPanel6.setkEndColor(new java.awt.Color(255, 153, 51));
        kGradientPanel6.setkStartColor(new java.awt.Color(255, 153, 51));

        TotalTransaksi2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TotalTransaksi2.setForeground(new java.awt.Color(255, 255, 255));
        TotalTransaksi2.setText("Total Transaksi");

        totalTrx.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        totalTrx.setForeground(new java.awt.Color(255, 255, 255));
        totalTrx.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalTrx.setText("0");

        javax.swing.GroupLayout kGradientPanel6Layout = new javax.swing.GroupLayout(kGradientPanel6);
        kGradientPanel6.setLayout(kGradientPanel6Layout);
        kGradientPanel6Layout.setHorizontalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel6Layout.createSequentialGroup()
                        .addComponent(TotalTransaksi2)
                        .addGap(0, 108, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(totalTrx, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        kGradientPanel6Layout.setVerticalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TotalTransaksi2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalTrx, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        roundedDesktopPane1.add(kGradientPanel6);
        kGradientPanel6.setBounds(10, 20, 240, 110);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public int getTotalPenjualan() {
        int total = 0;
        String sql = "SELECT count(*) AS total_penjualan FROM penjualan";

        try {
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                total = rs.getInt("total_penjualan");
            }

            rs.close();
            stmt.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return total;
    }
    
    public int getTotalBarang() {
        int total = 0;
        String sql = "SELECT COUNT(*) AS total_barang FROM masterbarang";

        try {
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                total = rs.getInt("total_barang");
            }

            rs.close();
            stmt.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return total;
    }
    
    public int getTotalPelanggan() {
        int total = 0;
        String sql = "SELECT COUNT(*) AS total_pelanggan FROM pelanggan";

        try {
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                total = rs.getInt("total_pelanggan");
            }

            rs.close();
            stmt.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return total;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TotalTransaksi2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    public keeptoo.KGradientPanel kGradientPanel6;
    private custom.RoundedDesktopPane roundedDesktopPane1;
    public static javax.swing.JLabel totalBrg;
    public static javax.swing.JLabel totalPlg;
    public static javax.swing.JLabel totalTrx;
    // End of variables declaration//GEN-END:variables
}
