/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import com.jtattoo.plaf.DecorationHelper;
import com.jtattoo.plaf.mint.MintLookAndFeel;
import control.control_login;
import java.awt.Color;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import keeptoo.Drag;
/**
 *
 * @author handa
 */
public class Login extends javax.swing.JFrame {
control_login cl;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
           cl = new control_login();
        this.setLocationRelativeTo(null);
        setTitle("LOGIN");
        
       KeyboardFocusManager.getCurrentKeyboardFocusManager().addKeyEventDispatcher(new KeyEventDispatcher() {
    private StringBuilder rfidBuffer = new StringBuilder();
    private Timer rfidTimer;

    @Override
    public boolean dispatchKeyEvent(KeyEvent e) {
        if (!Login.this.isActive()) return false; // <- Tambahkan ini

        if (e.getID() == KeyEvent.KEY_PRESSED) {
            char keyChar = e.getKeyChar();

            if (Character.isLetterOrDigit(keyChar)) {
                rfidBuffer.append(keyChar);
                if (rfidTimer != null) rfidTimer.stop();

                rfidTimer = new Timer(100, evt -> {
                    if (rfidBuffer.length() >= 10) {
                        String rfid = rfidBuffer.toString();
                        loginDenganRFID(rfid);
                    }
                    rfidBuffer.setLength(0);
                });
                rfidTimer.setRepeats(false);
                rfidTimer.start();
            }
        }

        return false;
    }
});
    }
    private void loginDenganRFID(String rfid_tag) {
    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemkasir", "root", "");
        String query = "SELECT * FROM user WHERE rfid_tag = ?";
        PreparedStatement ps = conn.prepareStatement(query);
        ps.setString(1, rfid_tag);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            String nama = rs.getString("nama");
            String userRFID = rs.getString("username");

            FormUtama frm = new FormUtama();
            frm.setVisible(true);
            frm.pengguna.setText(nama);

            JOptionPane.showMessageDialog(this, "Login berhasil via RFID untuk " + userRFID);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "RFID tidak terdaftar!", "Login Gagal", JOptionPane.ERROR_MESSAGE);
        }

        rs.close();
        ps.close();
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat login RFID: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        checkpass = new javax.swing.JCheckBox();
        custom_ButtonRounded1 = new custom.Custom_ButtonRounded();
        Register = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ForgetPass = new javax.swing.JLabel();
        txUsername = new javax.swing.JTextField();
        txPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkpassActionPerformed(evt);
            }
        });
        jPanel1.add(checkpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, 30, -1));

        custom_ButtonRounded1.setText("Login");
        custom_ButtonRounded1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custom_ButtonRounded1ActionPerformed(evt);
            }
        });
        jPanel1.add(custom_ButtonRounded1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 140, 40));

        Register.setText("Registrasi");
        Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterMouseClicked(evt);
            }
        });
        jPanel1.add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, -1, 20));

        jLabel3.setText("Belum punya akun?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 210, 20));

        ForgetPass.setText("Lupa password?");
        ForgetPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForgetPassMouseClicked(evt);
            }
        });
        jPanel1.add(ForgetPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 100, 20));

        txUsername.setBorder(null);
        jPanel1.add(txUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 180, 20));

        txPass.setBorder(null);
        jPanel1.add(txPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 180, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LOGIN UK FIX.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1284, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ForgetPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgetPassMouseClicked
    ForgetPass forgetPass = new ForgetPass(); 
    forgetPass.setVisible(true); 
    this.dispose();
    }//GEN-LAST:event_ForgetPassMouseClicked

    private void custom_ButtonRounded1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custom_ButtonRounded1ActionPerformed
         try {
        String user = txUsername.getText();
        char[] passArray = txPass.getPassword();
        String pass = new String(passArray);
        
        // Menggunakan metode login untuk mengecek kredensial
        boolean loginSuccess = cl.login(user, pass); 
        
        // Jika login berhasil, ambil data user
        if (loginSuccess) {
            ResultSet rs = cl.getUserData(user); // Ambil data user setelah login berhasil
            if (rs.next()) {
                FormUtama frm = new FormUtama();
                FormUtama.pengguna.setText(rs.getString("nama")); // Menampilkan nama pengguna di FormUtama
                dispose(); // Menutup window login
                frm.setVisible(true); // Menampilkan FormUtama
                JOptionPane.showMessageDialog(rootPane, "Selamat Datang " + rs.getString("username"));
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Username atau Password salah, Silahkan coba kembali");
        }
    } catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(rootPane, "GAGAL KONEK KE DATABASE KARENA " + ex);
    } catch (NoSuchAlgorithmException ex) {
    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(rootPane, "Algoritma hashing tidak tersedia.");
    }
    }//GEN-LAST:event_custom_ButtonRounded1ActionPerformed

    private void RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterMouseClicked
        Registrasi Registrasi = new Registrasi();
        Registrasi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegisterMouseClicked

    private void checkpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkpassActionPerformed
          if (checkpass.isSelected()) {
        txPass.setEchoChar((char) 0);
    } else {
        txPass.setEchoChar('*'); 
    }
    }//GEN-LAST:event_checkpassActionPerformed

   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ForgetPass;
    private javax.swing.JLabel Register;
    private javax.swing.JCheckBox checkpass;
    private custom.Custom_ButtonRounded custom_ButtonRounded1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txPass;
    private javax.swing.JTextField txUsername;
    // End of variables declaration//GEN-END:variables
}
