/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import control.registrasi;
import java.awt.Color;
import javax.swing.JOptionPane;
/**
 *
 * @author handa
 */
public class Registrasi extends javax.swing.JFrame {
 
    
    public Registrasi() {
        initComponents();
        labelLogin = new javax.swing.JLabel();
labelLogin.setFont(new java.awt.Font("Tahoma", 0, 18));
labelLogin.setForeground(new java.awt.Color(255, 255, 255));
labelLogin.setText("Login");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_registrasi = new custom.Custom_ButtonRounded();
        labelLogin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txPass = new javax.swing.JPasswordField();
        txNo = new javax.swing.JTextField();
        txNama = new javax.swing.JTextField();
        rfid_tag = new javax.swing.JTextField();
        txUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_registrasi.setText("Registrasi");
        btn_registrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrasiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_registrasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 425, 70, 30));

        labelLogin.setText("Login");
        labelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLoginMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelLoginMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                labelLoginMouseReleased(evt);
            }
        });
        jPanel1.add(labelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, -1, -1));

        jLabel2.setBackground(new java.awt.Color(222, 222, 222));
        jLabel2.setText("Sudah punya akun? ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 110, -1));

        txPass.setBorder(null);
        txPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPassActionPerformed(evt);
            }
        });
        jPanel1.add(txPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 180, 20));

        txNo.setBorder(null);
        jPanel1.add(txNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 180, 20));

        txNama.setBorder(null);
        txNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNamaActionPerformed(evt);
            }
        });
        jPanel1.add(txNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 180, 20));

        rfid_tag.setBorder(null);
        rfid_tag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfid_tagActionPerformed(evt);
            }
        });
        jPanel1.add(rfid_tag, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 245, 180, 20));

        txUsername.setBorder(null);
        txUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(txUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 180, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/REGISTER PALING BARU .png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPassActionPerformed

    private void labelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLoginMouseClicked

        Login Loginform = new Login(); 
    Loginform.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_labelLoginMouseClicked

    private void txNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNamaActionPerformed

    private void rfid_tagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfid_tagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rfid_tagActionPerformed

    private void txUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txUsernameActionPerformed

    private void btn_registrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrasiActionPerformed
     String username = txUsername.getText();
        String password = new String(txPass.getPassword());
        String nama = txNama.getText();
        String nomer = txNo.getText();
        String rfid = rfid_tag.getText();
         if (password.length() < 6) {
            JOptionPane.showMessageDialog(this, "Password minimal harus 6 karakter!", "Peringatan", JOptionPane.WARNING_MESSAGE);
      
            return; 
        }

       registrasi registerControl = new registrasi();

        if (registerControl.checkUsernameExists(username)) {
            JOptionPane.showMessageDialog(this, "Username sudah digunakan!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            boolean success = registerControl.registerUser(username, password, nama, nomer, rfid);
            if (success) {
                JOptionPane.showMessageDialog(this, "Registrasi berhasil! Silakan login.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                
               
                Login loginForm = new Login();
                loginForm.setVisible(true);
                this.dispose(); 
            } else {
                JOptionPane.showMessageDialog(this, "Registrasi gagal!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_registrasiActionPerformed

    private void labelLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLoginMousePressed
labelLogin.setForeground(Color.YELLOW); 
    }//GEN-LAST:event_labelLoginMousePressed

    private void labelLoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLoginMouseReleased
         labelLogin.setForeground(Color.WHITE);
    }//GEN-LAST:event_labelLoginMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private custom.Custom_ButtonRounded btn_registrasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JTextField rfid_tag;
    private javax.swing.JTextField txNama;
    private javax.swing.JTextField txNo;
    private javax.swing.JPasswordField txPass;
    private javax.swing.JTextField txUsername;
    // End of variables declaration//GEN-END:variables
}
