/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import control.control_resetPass;
import javax.swing.JOptionPane;
/**
 *
 * @author handa
 */
public class ResetPass extends javax.swing.JFrame {

    /**
     * Creates new form ResetPass
     */
    public ResetPass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_reset = new javax.swing.JButton();
        checkpass = new javax.swing.JCheckBox();
        txConfirmPass = new javax.swing.JPasswordField();
        txNewPass = new javax.swing.JPasswordField();
        txUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_reset.setBackground(new java.awt.Color(255, 255, 255));
        btn_reset.setForeground(new java.awt.Color(0, 0, 0));
        btn_reset.setText("RESET");
        btn_reset.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel1.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 130, 30));

        checkpass.setBackground(new java.awt.Color(255, 255, 255));
        checkpass.setForeground(new java.awt.Color(0, 0, 0));
        checkpass.setText(" Tunjukkan Password");
        checkpass.setBorder(null);
        checkpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkpassActionPerformed(evt);
            }
        });
        jPanel1.add(checkpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, -1, -1));

        txConfirmPass.setBackground(new java.awt.Color(255, 255, 255));
        txConfirmPass.setBorder(null);
        jPanel1.add(txConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 180, -1));

        txNewPass.setBackground(new java.awt.Color(255, 255, 255));
        txNewPass.setBorder(null);
        jPanel1.add(txNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 325, 180, -1));

        txUsername.setBackground(new java.awt.Color(255, 255, 255));
        txUsername.setBorder(null);
        jPanel1.add(txUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 275, 180, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/RESET PASSWORD (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1282, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
         String username = txUsername.getText();
    String newPassword = new String(txNewPass.getPassword());
    String confirmPassword = new String(txConfirmPass.getPassword());

    
    if (username.isEmpty() || newPassword.isEmpty() || confirmPassword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Harap isi semua kolom!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    
    if (!newPassword.equals(confirmPassword)) {
        JOptionPane.showMessageDialog(this, "Password baru tidak cocok!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

       control_resetPass control = new control_resetPass();
    boolean resetSuccess = control.resetPassword(username, newPassword);

    if (resetSuccess) {
        JOptionPane.showMessageDialog(this, "Password berhasil direset! Silakan login kembali.", "Sukses", JOptionPane.INFORMATION_MESSAGE);

        
        Login loginform = new Login(); 
        loginform.setVisible(true);
        this.dispose(); 
    } else {
        JOptionPane.showMessageDialog(this, "Gagal mereset password. Periksa kembali username!", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btn_resetActionPerformed

    private void checkpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkpassActionPerformed
       if (checkpass.isSelected()) {
        txNewPass.setEchoChar((char) 0);
        txConfirmPass.setEchoChar((char) 0);
    } else {
        txNewPass.setEchoChar('*'); 
        txConfirmPass.setEchoChar('*');
    }
    }//GEN-LAST:event_checkpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResetPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reset;
    private javax.swing.JCheckBox checkpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txConfirmPass;
    private javax.swing.JPasswordField txNewPass;
    private javax.swing.JTextField txUsername;
    // End of variables declaration//GEN-END:variables
}
